[variables]
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build] 
cmds = ["cd backend && npm run build"]

[phases.start]
cmd = "cd backend && npm run db:migrate && npm start"